# Generated by Django 4.1.4 on 2023-01-19 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('breakeven_point', models.PositiveIntegerField()),
                ('exchange', models.CharField(max_length=10)),
                ('segment', models.CharField(max_length=10)),
                ('entry_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('target', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('stoploss', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_outputs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
