# Generated by Django 4.1.4 on 2023-01-22 08:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0006_rename_importtrade_importtrades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ImportTrades',
            new_name='ImportTrade',
        ),
    ]
