# Generated by Django 4.1.4 on 2023-01-22 13:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0007_rename_importtrades_importtrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('isin', models.CharField(max_length=15)),
                ('trade_date', models.DateField()),
                ('exchange', models.CharField(max_length=10)),
                ('segment', models.CharField(max_length=10)),
                ('series', models.CharField(max_length=10)),
                ('trade_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('trade_id', models.CharField(max_length=20)),
                ('order_id', models.CharField(max_length=50)),
                ('order_exec_time', models.DateTimeField(verbose_name='Order Execution Time')),
                ('is_open', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order_exec_time',),
            },
        ),
        migrations.AddField(
            model_name='trade',
            name='orders',
            field=models.ManyToManyField(related_name='trade', to='mainapp.mergedtrade'),
        ),
    ]
