# Generated by Django 4.1.4 on 2023-01-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_mergedtrade_trade_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='brocker',
            name='assets_rule',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='brocker',
            name='fields_rule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
