# Generated by Django 4.1.4 on 2023-01-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_brocker_assets_rule_brocker_fields_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brocker',
            name='assets_rule',
            field=models.TextField(blank=True, default="{\n    'cash': [None, ''],\n    'equity_options': [[None, ''], [None, '']],\n    'equity_futures': [[None, ''], [None, '']],\n    'forex_spot':  [None, ''],\n    'forex_options': [[None, ''], [None, '']],\n    'forex_futures': [[None, ''], [None, '']],\n    'commodity_futures': [[None, ''], [None, '']],\n    'commodity_options': [[None, ''], [None, '']],\n    'crypto_spot': [None, ''],\n    'crypto_futures':  [None, ''],\n    'crypto_options':  [None, ''],\n}\n", null=True),
        ),
        migrations.AlterField(
            model_name='brocker',
            name='fields_rule',
            field=models.TextField(blank=True, default="{\n    'symbol': [None, ''],\n    'trade_date': [None, ''],\n    'exchange': [None, ''],\n    'segment': [None, ''],\n    'trade_type': [None, ''],\n    'quantity': [None, ''],\n    'price': [None, ''],\n    'order_id': [None, ''],\n    'order_execution_time': [None, ''],\n    'strike_price': [None, ''],\n    'expiry_date': [None, ''],\n    'options_type': [0, r'.*'],\n}", null=True),
        ),
    ]
