# Generated by Django 4.1.4 on 2023-01-23 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0012_alter_mergedtrade_options_remove_mergedtrade_is_open_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brocker',
            name='fields_rule',
            field=models.TextField(default="{\n    'symbol': [None, ''],\n    'trade_date': [None, ''],\n    'exchange': [None, ''],\n    'segment': [None, ''],\n    'trade_type': [None, ''],\n    'quantity': [None, ''],\n    'price': [None, ''],\n    'order_id': [None, ''],\n    'order_execution_time': [None, ''],\n    'strike_price': [None, ''],\n    'expiry_date': [None, ''],\n}"),
        ),
        migrations.AlterField(
            model_name='mergedtrade',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
