# Generated by Django 4.1.4 on 2023-01-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_brocker_fields_rule_alter_mergedtrade_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergedtrade',
            name='exchange',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mergedtrade',
            name='order_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mergedtrade',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mergedtrade',
            name='quantity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='mergedtrade',
            name='segment',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mergedtrade',
            name='series',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mergedtrade',
            name='strike_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='mergedtrade',
            name='symbol',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mergedtrade',
            name='trade_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell')], max_length=4, null=True),
        ),
    ]
