# Generated by Django 4.1.4 on 2023-01-28 19:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0024_alter_trade_merged_trades'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trade',
            new_name='TradeHistory',
        ),
    ]
