# Generated by Django 4.1.4 on 2023-02-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0027_alter_brocker_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='type',
            field=models.IntegerField(choices=[(0, 'Import'), (1, 'Sync'), (2, 'Manual')], default=0),
        ),
        migrations.AlterField(
            model_name='brocker',
            name='rules',
            field=models.TextField(default="{\n    'symbol':{\n        'type': 'field',\n        'col': 0,\n        'regex': r'(?P<value>.*)'\n    },\n    'tradeDate': {\n        'type': 'field',\n        'col': 2,\n        'regex': r'(?P<value>.*)'\n    },\n    'exchange': {\n        'type': 'field',\n        'col': 3,\n        'regex': r'(?P<value>.*)'\n    },\n    'segment': {\n        'type': 'field',\n        'col': 4,\n        'regex': r'(?P<value>.*)'\n    },\n    'quantity': {\n        'type': 'field',\n        'col': 8,\n        'regex': r'(?P<value>.*)'\n    },\n    'price': {\n        'type': 'field',\n        'col': 9,\n        'regex': r'(?P<value>.*)'\n    },\n    'orderId':{\n        'type': 'field',\n        'col': 11,\n        'regex': r'(?P<value>.*)',\n    },\n    'executionTime': {\n        'type': 'field',\n        'col': 12,\n        'regex': r'.*(?P<value>\\d\\d:\\d\\d:\\d\\d)$'\n    },\n    'optionsType': {\n        'type': 'check',\n        'values': {\n            'puts': [\n                {\n                    'col': 0,\n                    'regex': '.*\\d(PE)$'\n                }\n            ],\n            'calls': [\n                {\n                    'col': 0,\n                    'regex': '.*\\d(CE)$'\n                }\n            ]\n        }\n    },\n    'tradeType': {\n        'type': 'check',\n        'values': {\n            'sell': [\n                {\n                    'col': 6,\n                    'regex': r'^(sell)$'\n                }\n            ],\n            'buy': [\n                {\n                    'col': 6,\n                    'regex': r'^(buy)$'\n                }\n            ]\n        }\n    },\n    'assetType': {\n        'type': 'check',\n        'values': {\n            'cash': [\n                {\n                    'col': 4,\n                    'regex': r'^EQ$'\n                }\n            ],\n            'equity_options': [\n                {\n                    'col': 4,\n                    'regex': r'^FO$'\n                },\n                {\n                    'col': 0, \n                    'regex': r'.*(CE|PE)$'\n                }\n            ],\n            'equity_futures': [\n                {\n                    'col': 4,\n                    'regex': r'^FO$'\n                },\n                {\n                    'col': 0, \n                    'regex': r'.*(FUT$)'\n                }\n            ],\n            'forex_options': [\n                {\n                    'col': 4,\n                    'regex': r'^CDS$'\n                },\n                {\n                    'col':0, \n                    'regex': r'.*(CE|PE)$'\n                }\n            ],\n            'forex_futures': [\n                {\n                    'col': 4,\n                    'regex': r'^CDS$'\n                },\n                {\n                    'col': 0, \n                    'regex': r'.*(FUT)$'\n                }\n            ],\n            'commodity_options': [\n                {\n                    'col': 4,\n                    'regex': r'^COM$'\n                },\n                {\n                    'col': 0, \n                    'regex': r'.*(CE|PE)$'\n                }\n            ],\n            'commodity_futures': [\n                {\n                    'col': 4,\n                    'regex': r'^COM$'\n                },\n                {\n                    'col': 0, \n                    'regex': r'.*(FUT)$'\n                }\n            ],\n        }\n    }\n}"),
        ),
    ]
