# Generated by Django 4.1.4 on 2023-02-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0028_tradehistory_type_alter_brocker_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='no_executions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='no_trades',
            field=models.IntegerField(default=0),
        ),
    ]
