# Generated by Django 4.1.4 on 2023-02-07 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0029_tradehistory_no_executions_tradehistory_no_trades'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='tradehistory',
            name='brocker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.brocker'),
        ),
    ]
