# Generated by Django 4.1.4 on 2023-02-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0031_alter_tradehistory_user_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
