# Generated by Django 4.1.4 on 2023-02-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0032_comparison_is_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comparison',
            name='filters1',
            field=models.JSONField(blank=True, default='{}', null=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='filters2',
            field=models.JSONField(blank=True, default='{}', null=True),
        ),
    ]
