# Generated by Django 4.1.4 on 2023-03-07 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0037_rename_portfolio_portfolioentry_entries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioentry',
            old_name='entries',
            new_name='portfolio',
        ),
    ]
