# Generated by Django 4.1.4 on 2023-01-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earlyaccessuser',
            name='segment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='earlyaccessuser',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
