# Generated by Django 4.1.4 on 2023-01-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_firstname_remove_profile_secondname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone',
            new_name='phoneNumber',
        ),
    ]
